import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles({
  root: {
    margin: "30px 0",
    fontFamily: "Poppins",
  },
  nav: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "30px",
  },
  paper: {
    display: "flex",
  },
  backArrow: {
    color: "#8967fc",
    fontSize: "30px",
    marginRight: "5px",
  },
  title: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "24px",
    color: "#303030",
    marginLeft: "2px",
    marginTop: "5px",
  },
  actionButtons: {
    border: "1px solid #EFF0F6",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "100px",
    marginLeft: "10px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "14px",
    padding: "10px 30px",
  },
  sendActionButton: {
    border: "1px solid #EFF0F6",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "100px",
    marginLeft: "10px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "14px",
    padding: "10px 30px",
    background: "#8967FC",
    color: "#fff",
    "&:hover, &:focus": {
      color: "#8967FC",
    },
  },
  itemActionBtn: {
    color: "#8967FC",
    border: "1px solid #8967FC",
    borderRadius: "100px",
    padding: "10px 20px",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontSize: "16px",
    marginTop: "20px",
    marginRight: "20px",
  },
  table: {
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
  },
  totalRow: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "16px",
    color: "#8967FC",
    textAlign: "justify",
    paddingLeft: "30px",
  },
  card: {
    marginTop: "30px",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
  },
  cardTitle: {
    fontFamily: "Poppins",
    fontWeight: 600,
    fontSize: "16px",
    color: "#303030",
    padding: "5px 15px",
  },
  cardContent: {
    fontFamily: "Poppins",
    fontSize: "14px",
    color: "#7D7D7D",
    padding: "5px 15px",
  },
  addItemBtn: {
    background: "#8967FC",
    color: "#fff",
    border: "2px solid #8967FC",
    borderRadius: "100px",
    padding: "10px 20px",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontSize: "16px",
    marginTop: "20px",
    "&:hover, &:focus": {
      color: "#8967FC",
    },
  },
  modal: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "640px",
    background: "#fff",
    border: "0.75px solid #EFF0F6",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "7.5px",
  },
  modalTitle: {
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "24px",
    color: "#303030",
    margin: "5% 2%",
  },

  inputLabel: {
    fontWeight: 600,
    marginBottom: '0.2rem'
  },

  inputs: {
    border: "0.75px solid #EFF0F6",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "5px",
    fontFamily: "Poppins",
    fontSize: 14,
    padding: '0.5rem 2%',
    width: "96%",
  },
  modalButton: {
    border: "1px solid #EFF0F6",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "10px",
    margin: "3% 20px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "14px",
    padding: "10px 25px",
    background: "#8967FC",
    color: "#fff",
  },
  taxDialogTitle: {
    fontWeight: "600",
    fontSize: "1.5rem",
    lineHeight: "1.5rem",
    marginTop: "2%",
    marginBottom: "3%",
  },
  taxDialogError: {
    fontSize: "1rem",
    lineHeight: "1rem",
    marginTop: "2%",
    marginBottom: "2%",
    color: "red",
  },
  addItemBtnHover: {
    color: "#8967FC",
  },
  hidden: {
    height: 0,
    width: 0,
    display: "none",
  },
  editButton: {
    color: "#7D7D7D",
    width: "1.8rem",
    height: "2rem",
    "&:hover, &:focus": {
      color: "#8967FC",
    },
  },
  deleteButton: {
    width: "1.8rem",
    height: "1.8rem",
    color: "#7D7D7D",
    "&:hover, &:focus": {
      color: "red",
    },
  },

  buttonDisabled: {
    cursor: "not-allowed",
    color: "#b6a2fc",
    pointerEvents: "none",
    border: "1px solid #b6a2fc",
  },
  conversationContainer: {
    width: "96%",
    marginTop: "2%",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
    padding: "20px",
    heigth: "200px",
  },
  conversation: {
    display: "flex",
    flexDirection: "column-reverse",
    paddingRight: "0.5em",
    maxHeight: "30em",
    overflowY: "scroll",
    "&::-webkit-scrollbar": {
      width: "0.4em",
    },
    "&::-webkit-scrollbar-track": {
      boxShadow: "inset 0 0 6px rgba(0,0,0,0.00)",
      webkitBoxShadow: "inset 0 0 6px rgba(0,0,0,0.00)",
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(0,0,0,.1)",
      outline: "1px solid slategrey",
      borderRadius: "10px",
    },
  },
});
