import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles({
  root: {
    margin: "30px 0",
    width: "100%",
  },
  container: {
    width: "98%",
    height: "222px",
    left: "286px",
    top: "196px",
    background: "#fff",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
    marginTop: "20px",
    padding: "20px",
    display: "flex",
  },
  projectHeader: {
    width: "98%",
    height: "222px",
    left: "286px",
    top: "196px",
    background: "#fff",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
    marginTop: "20px",
    padding: "20px",
  },
  projectHeaderContent: {
    width: "100%",
    height: "180px",
    background: "#fff",
    display: "flex",
  },
  imageContainer: {
    width: "130px",
    height: "135px",
    paddingLeft: "20px",
    paddingTop: "30px",
    background: "#DFE6EC",
    opacity: 0.7,
    borderRadius: "10px",
    marginRight: "20px",
  },
  paper: {
    display: "flex",
    marginTop: "30px",
  },
  avatar: {
    color: "#8967fc",
    backgroundColor: "#fff",
    fontSize: "24px",
  },
  title: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "24px",
    color: "#303030",
    marginLeft: "2px",
  },
  cardTitle: {
    fontFamily: "Poppins",
    fontWeight: 600,
    fontSize: "20px",
    color: "#303030",
  },
  cardSubTitle: {
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "16px",
    color: "#7D7D7D",
    marginTop: "5px",
  },
  assetContainer: {
    width: "985px",
    height: "222px",
    left: "286px",
    top: "196px",
    background: "#fff",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
    marginTop: "20px",
    padding: "20px",
  },
  conversationContainer: {
    width: "97%",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
    padding: "20px",
    heigth: "200px",
  },
  conversation: {
    display: "flex",
    flexDirection: "column-reverse",
    paddingRight: "0.5em",
    maxHeight: "30em",
    overflowY: "scroll",
    "&::-webkit-scrollbar": {
      width: "0.4em",
    },
    "&::-webkit-scrollbar-track": {
      boxShadow: "inset 0 0 6px rgba(0,0,0,0.00)",
      webkitBoxShadow: "inset 0 0 6px rgba(0,0,0,0.00)",
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(0,0,0,.1)",
      outline: "1px solid slategrey",
      borderRadius: "10px",
    },
  },
  submit: {
    backgroundColor: "#8967fc",
    alignSelf: "center",
    borderRadius: "100px",
    float: "left",
    maxWidth: "100%",
    color: "#fff",
    height: "50px",
    fontSize: 16,
    "@media (max-width: 768px)": {
      width: "100px",
      height: "50px",
    },
  },
});
