import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles({
  root: {
    margin: "30px 0",
    fontFamily: "Poppins",
  },
  nav: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "30px",
  },
  paper: {
    display: "flex",
  },
  backArrow: {
    color: "#8967fc",
    fontSize: "30px",
    marginRight: "5px",
  },
  title: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "24px",
    color: "#303030",
    marginLeft: "2px",
    marginTop: "5px",
  },
  actionButtons: {
    border: "1px solid #EFF0F6",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "100px",
    marginLeft: "10px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "14px",
    padding: "10px 30px",
  },
  itemActionBtn: {
    color: "#8967FC",
    border: "1px solid #8967FC",
    borderRadius: "100px",
    padding: "10px 40px",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontSize: "16px",
    marginTop: "20px",
    marginRight: "20px",
  },
  table: {
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
  },
  totalRow: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "16px",
    color: "#8967FC",
    textAlign: "justify",
    paddingLeft: "30px",
  },
  addItemBtn: {
    background: "#8967FC",
    color: "#fff",
    border: "2px solid #8967FC",
    borderRadius: "100px",
    padding: "10px 20px",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontSize: "16px",
    marginTop: "20px",
    "&:hover, &:focus": {
      color: "#8967FC",
    },
  },
  modal: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "400px",
    background: "#fff",
    border: "0.75px solid #EFF0F6",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
    padding: "5px 25px",
  },
  modalTitle: {
    fontFamily: "Poppins",
    fontSize: "20px",
    padding: "10px 0",
    borderRadius: "10px 10px 0px 0px",
  },
  inputName: {
    borderRadius: "30px",
    padding: "5px 15px",
    width: "50%",
    border: "1px solid #EFF0F6",
    background: "#fff",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
  },
  container: {
    backgroundColor: "#EFF0F6",
    borderRadius: "5px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    padding: "15px 25px",
  },
  nameInputContainer: { display: "flex", width: "100%", marginBottom: "15px" },
  inputTitle: {
    width: "30%",
    display: "flex",
    alignItems: "center",
  },
  addUserBtn: {
    color: "#8967FC",
    fontFamily: "Poppins",
    fontWeight: "700",
    fontSize: "15px",
    textDecoration: "none",
    marginTop: "0px",
  },
});
