import { makeStyles } from "@material-ui/core/styles";

export const useTableStyles = makeStyles((theme) => ({
  root: {},
  table: {
    width: "1290px",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
  },
  row: {
    height: "42px",
    display: "flex",
    alignItems: "center",
    marginTop: theme.spacing(1),
  },
  spacer: {
    flexGrow: 1,
  },
  importButton: {
    marginRight: theme.spacing(1),
  },
  exportButton: {
    marginRight: theme.spacing(1),
  },
  searchInput: {
    marginRight: theme.spacing(1),
  },
  content: {
    marginTop: theme.spacing(2),
  },
  tableContent: {
    padding: 0,
    marginBottom: "50px",
  },
  inner: {},
  nameContainer: {
    display: "flex",
    alignItems: "center",
  },
  hidden: {
    height: 0,
    width: 0,
    display: "none",
  },
  avatar: {
    marginRight: theme.spacing(2),
  },
  clientActions: {
    display: "flex",
    justifyContent: "space-between",
  },
  clientAction: {
    display: "flex",
    justifyContent: "flex-end",
  },
  actions: {
    justifyContent: "flex-end",
  },
  addSubscription: {
    color: "#8967FC",
    fontFamily: "Poppins",
    fontWeight: "700",
    fontSize: "18px",
    textDecoration: "none",
  },
}));

export const useStyles = makeStyles({
  root: {
    margin: "30px 0",
    fontFamily: "Poppins",
  },
  nav: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "30px",
  },
  paper: {
    display: "flex",
  },
  backArrow: {
    color: "#8967fc",
    fontSize: "30px",
    marginRight: "5px",
  },
  backArrowTitle: {
    color: "#8967fc",
    fontSize: "30px",
    marginRight: "5px",
  },
  title: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "24px",
    color: "#303030",
    marginLeft: "2px",
    marginTop: "5px",
  },
  screenTitle: {
    fontFamily: "Poppins",
    fontWeight: "700",
    fontSize: "20px",
    color: "#303030",
    textAlign: "center",
  },
  titleContainer: {
    display: "flex",
    flexDirection: "row",
    height: "30px",
    marginBottom: "15px",
  },
  screenContainer: {
    paddingTop: "15px",
  },
  actionButtons: {
    border: "1px solid #EFF0F6",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "100px",
    marginLeft: "10px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "14px",
    padding: "10px 30px",
  },
  sendActionButton: {
    border: "1px solid #EFF0F6",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "100px",
    marginLeft: "10px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "14px",
    padding: "10px 30px",
    background: "#8967FC",
    color: "#fff",
    "&:hover, &:focus": {
      color: "#8967FC",
    },
  },
  itemActionBtn: {
    color: "#8967FC",
    border: "1px solid #8967FC",
    borderRadius: "100px",
    padding: "10px 20px",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontSize: "16px",
    marginTop: "20px",
    marginRight: "20px",
  },
  table: {
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
  },
  totalRow: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "16px",
    color: "#8967FC",
    textAlign: "justify",
    paddingLeft: "30px",
  },
  card: {
    marginTop: "30px",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
  },
  cardTitle: {
    fontFamily: "Poppins",
    fontWeight: 600,
    fontSize: "16px",
    color: "#303030",
    padding: "10px 20px",
  },
  cardContent: {
    fontFamily: "Poppins",
    fontSize: "14px",
    color: "#7D7D7D",
    padding: "10px 20px",
  },
  addItemBtn: {
    background: "#8967FC",
    color: "#fff",
    border: "2px solid #8967FC",
    borderRadius: "100px",
    padding: "10px 20px",
    fontFamily: "Poppins",
    fontWeight: 500,
    fontSize: "16px",
    marginTop: "20px",
    "&:hover, &:focus": {
      color: "#8967FC",
    },
  },
  modal: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "550px",
    background: "#fff",
    border: "0.75px solid #EFF0F6",
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
  },
  modalTitle: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "20px",
    color: "#fff",
    textAlign: "center",
    padding: "10px 0",
    background: "#8967FC",
    borderRadius: "10px 10px 0px 0px",
  },
  inputName: {
    borderRadius: "100px",
    padding: "8px 0",
    textAlign: "center",
    marginTop: "20px",
    marginBottom: "20px",
    marginLeft: "40px",
    width: "85%",
    fontFamily: "Poppins",
    fontSize: 14,
    color: "#7D7D7D",
    fontWeight: 400,
    border: "1px solid #EFF0F6",
    background: "#EFF0F6",
  },
  inputNumber: {
    border: "0.75px solid #EFF0F6",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "100px",
    padding: "10px",
    margin: "10px",
    width: "40%",
    fontFamily: "Poppins",
    fontSize: 14,
  },
  modalButton: {
    border: "1px solid #EFF0F6",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "10px",
    margin: "3% 20px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "14px",
    padding: "10px 25px",
    background: "#8967FC",
    color: "#fff",
  },
  taxDialogTitle: {
    fontWeight: "600",
    fontSize: "1.5rem",
    lineHeight: "1.5rem",
    marginTop: "2%",
    marginBottom: "3%",
  },
  taxDialogError: {
    fontSize: "1rem",
    lineHeight: "1rem",
    marginTop: "2%",
    marginBottom: "2%",
    color: "red",
  },
  addItemBtnHover: {
    color: "#8967FC",
  },
  hidden: {
    height: 0,
    width: 0,
    display: "none",
  },
  editButton: {
    color: "#7D7D7D",
    width: "1.8rem",
    height: "2rem",
    "&:hover, &:focus": {
      color: "#8967FC",
    },
  },
  deleteButton: {
    width: "1.8rem",
    height: "1.8rem",
    color: "#7D7D7D",
    "&:hover, &:focus": {
      color: "red",
    },
  },
  buttonDisabled: {
    cursor: "not-allowed",
    color: "#b6a2fc",
    pointerEvents: "none",
    border: "1px solid #b6a2fc",
  },
  comments: {
    background: "#8967FC",
    marginLeft: "auto",
    borderRadius: "20px 0 20px 20px",
    padding: "15px 20px",
    marginRight: "10px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "16px",
    color: "#fff",
    maxWidth: "70%",
  },
  commentDate: {
    display: "flex",
    justifyContent: "flex-end",
    paddingRight: "10px",
    fontFamily: "Poppins",
    fontWeight: 300,
    fontSize: "12px",
    color: "#303030",
  },
  myCommentsName: {
    marginLeft: "10px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "15px",
    color: "black",
  },
  CommentsName: {
    marginRight: "10px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "15px",
    color: "black",
    display: "flex",
    justifyContent: "flex-end",
  },
  myComments: {
    background: "#DFE6EC",
    borderRadius: "0px 20px 20px 20px",
    padding: "15px 20px",
    marginLeft: "10px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "16px",
    color: "#7D7D7D",
    maxWidth: "70%",
  },
  commentPositionRight: {
    display: "flex",
    justifyContent: "flex-end",
  },
  commentPositionLeft: {
    display: "flex",
    marginRight: "20px",
    justifyContent: "flex-start",
  },
  commentTime: {
    fontFamily: "Poppins",
    fontWeight: 300,
    fontSize: "12px",
    color: "#303030",
  },
  commentTimeRight: {
    textAlign: "right",
    paddingRight: "10px",
  },
  commentTimeLeft: {
    paddingLeft: "10px",
  },
  subscriptionContainer: {
    display: "flex",
    justifyContent: "space-between",
    height: "90vh",
  },
  subscriptionCard: {
    border: "1px solid #8967FC",
    boxShadow: "0px 3px 16.5px rgba(8, 15, 52, 0.03)",
    borderRadius: "16px",
    width: "300px",
    marginRight: "40px",
    position: "relative",
    height: "88vh",
  },
  privateSubscriptionCard: {
    borderRadius: "16px",
    background: "#303030",
    width: "300px",
    marginRight: "40px",
    position: "relative",
    height: "88vh",
  },
  privateSubscriptionCardAdmin: {
    width: "300px",
    margin: "0 35px",
    borderRadius: "16px",
    background: "#303030",
    position: "relative",
    display: "flex",
    height: "80vh",
  },
  subscriptionCardTitle: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "24px",
    color: "#303030",
    marginBottom: "20px",
  },
  privateSubscriptionCardTitle: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "24px",
    color: "#fff",
    marginBottom: "20px",
  },
  subscriptionPriceSection: {
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "16px",
    color: "#8967FC",
    marginBottom: "20px",
  },
  subscriptionPrice: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "18px",
    color: "#8967FC",
  },
  subscriptionSubTitle: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "16px",
    color: "#303030",
    margin: "10px 0",
  },
  privateSubscriptionSubTitle: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "16px",
    color: "#fff",
    margin: "5px 0",
    paddingBottom: "5px",
    borderBottom: "1px solid #7D7D7D",
  },
  checkListContainer: {
    height: "55vh",
    width: "17em",
    overflow: "auto",
    listStyle: "none",
    "&::-webkit-scrollbar": {
      width: "0.4em",
    },
    "&::-webkit-scrollbar-track": {
      boxShadow: "inset 0 0 6px rgba(0,0,0,0.00)",
      webkitBoxShadow: "inset 0 0 6px rgba(0,0,0,0.00)",
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(0,0,0,.1)",
      outline: "1px solid slategrey",
      borderRadius: "10px",
    },
  },
  checkListItem: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    margin: "10px 0",
    padding: 0,
  },
  couponListItem: {
    width: "100%",
    display: "flex",
    margin: "10px 0",
    height: "250px",
    padding: 0,
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  checkListText: {
    marginLeft: "10px",
    fontFamily: "Poppins",
    fontWeight: 400,
    fontSize: "16px",
    color: "#303030",
  },
  privateCheckListText: {
    marginLeft: "10px",
    fontFamily: "Poppins",
    fontWeight: 300,
    fontSize: "16px",
    color: "#fff",
  },
  subscriptionButton: {
    background: "#F8F4FF",
    borderRadius: "8px",
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "20px",
    color: "#8967FC",
    textAlign: "center",
    width: "90%",
    textTransform: "none",
    position: "absolute",
    bottom: "20px",
  },
  privateSubscriptionButton: {
    background: "#8967FC",
    borderRadius: "8px",
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "20px",
    color: "#fff",
    textAlign: "center",
    width: "90%",
    textTransform: "none",
    position: "absolute",
    bottom: "20px",
  },
  subscriptionDetailsTitle: {
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "20px",
    color: "#303030",
    marginBottom: "20px",
  },
  subscriptionDetailsCard: {
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    display: "grid",
    gridTemplateColumns: "50% 50%",
    padding: "20px 0",
  },
  privateSubscriptionDetailsCard: {
    boxShadow: "0px 0px 14px rgba(201, 215, 223, 0.2)",
    borderRadius: "10px",
  },
  SubcriptionDetail: {
    background: "#DFE6EC",
    opacity: "0.9",
    borderRadius: "20px",
    width: "250px",
    height: "70px",
    margin: "10px 20px",
    padding: "20px",
  },
  SubcriptionDetailTitle: {
    fontFamily: "Poppins",
    fontWeight: 500,
    fontSize: "18px",
    color: "#303030",
    marginBottom: "5px",
  },
  SubcriptionDetailText: {
    fontFamily: "Poppins",
    fontWeight: 500,
    fontSize: "16px",
    color: "#7D7D7D",
  },
  publicDiscount: {
    backgroundColor: "#8967FC",
    transform: "rotate(38deg)",
    borderRadius: "4px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "122px",
    padding: "5px 20px",
    position: "absolute",
    width: "165px",
    height: "39px",
    color: "#fff",
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "14px",
  },
  discount: {
    background: "#fff",
    transform: "rotate(38deg)",
    borderRadius: "4px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "122px",
    padding: "5px 20px",
    position: "absolute",
    width: "165px",
    height: "39px",
    color: "#8967FC",
    fontFamily: "Poppins",
    fontWeight: 700,
    fontSize: "14px",
  },
  paginationContainer: {
    display: "flex",
    justifyContent: "flex-end",
    paddingRight: "1.5em",
    alignItems: "center",
  },
  tableActions: {
    display: "flex",
    justifyContent: "space-between",
    padding: "0px 10px",
    width: "90%",
    position: "absolute",
    top: "95%",
    bottom: "0",
  },
  addCustomer: {
    color: "#8967FC",
    fontFamily: "Poppins",
    fontWeight: "700",
    fontSize: "18px",
    textDecoration: "none",
  },
  addUserBtn: {
    color: "#8967FC",
    fontFamily: "Poppins",
    fontWeight: "700",
    fontSize: "15px",
    textDecoration: "none",
    marginTop: "0px",
  },
});
